# Setup
title:        AndyMorphs
tagline:      I make videos
baseurl:      "https://link.andymorphs.com"
locale:       "en"

# About/contact
author:
  name:       Andy Morphs
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown